### ISSUE TITLE
Chapter 10 Exercise: ListsAndRecursion-5

### ISSUE THREAD

**Issue by kristofvanwoensel** [carlos4ndre/elixir-exercises#2]
Dear Carlos

Great solutions, it helps me alot!
The solution of the 'take' function is not completely correct.

take([1,2,3,4], -1) should return [4] and not [1,2,3].

I created a "reverse function" that reversed the list to [4,3,2,1] and passed 1 (instead of -1) as n and reversed the returned list again. It might not be the most efficient solution though.

**Comment by carlos4ndre** [comment]
@kristofvanwoensel Thanks for spotting this bug! I've added the reverse function as well, I guess it is good enough for the exercise. For better performance, I would use the same approach as the standard library, details [here](https://github.com/elixir-lang/elixir/blob/57d3afab16aca3432196fbcfba647899ab261e50/lib/elixir/lib/enum.ex#L2408)
