### ISSUE TITLE
Chapter 10 Exercise: ListsAndRecursion-8

### ISSUE THREAD

**Issue by kristofvanwoensel** [carlos4ndre/elixir-exercises#3]
A (in my opinion) cleaner solution:

	def tax(rates, orders) do
		for {city, rate} <- rates,[id: id, ship_to: ship_to, net_amount: net_amount] <- orders, ship_to == city, do: [id: id, ship_to: ship_to, net_amount: net_amount, total_amount: net_amount * rate]
	end

**Comment by carlos4ndre** [comment]
@kristofvanwoensel If I'm not mistaken, It only returns the orders that are taxable and we need them all. I've changed the existing code to make it more readable, keeping the order within the keyword list (probably not required, just to be consistent with the expected output).

```
  def buy(orders, tax_rates) do
    for order <- orders do
      net_amount = order[:net_amount]
      ship_to = order[:ship_to]
      tax_rate = calculate_tax_rate(ship_to, tax_rates)
      total_amount = calculate_total_amount(net_amount, tax_rate)

      order ++ [total_amount: total_amount]
    end
  end

  defp calculate_tax_rate(ship_to, tax_rates) do
    Keyword.get(tax_rates, ship_to, 0.0)
  end

  defp calculate_total_amount(net_amount, tax_rate), do: net_amount + net_amount * tax_rate
```
